language: julia
os: linux
julia: 0.5
notifications:
  email: false
env:
  - JULIA_NUM_THREADS=2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpich libmpich-dev
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Gasp")'
  - mpiexec.hydra -np 4 julia --depwarn=no test/dtreebench.jl
  - mpiexec.hydra -np 4 julia --depwarn=no test/garraytest.jl

